version: '3'
services:

  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  web:
    build: .
    depends_on:
      - db
    volumes:
      - ./public_html:/var/www/html
      - ./config/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  db-data: